### ISSUE TITLE
Design Doc Review (MVP + Schema) 

### ISSUE THREAD

**Issue by rlim92** [danemauland/sheriff_of_nottingham#1]
Hey Dane, design docs looking good so far! Some suggestions below: 

### MVP: 
- [ ] are `positions` a theme alternative to stocks invested in? 
- [ ] for `watchlist` users should be able to remove from their watchlist as well

### Schema: 
- [ ] there are no companies tied to the `trades`, add a table referring to the company
- [ ] `watchlists` and `companies` should have a many-to-many relationship, so that watchlists can have many companies and companies can be on many watchlists. A joins table is necessary for this

Great job so far! Let me know if you have any questions.

**Comment by danemauland** [comment]
MVP:

   - are positions a theme alternative to stocks invested in? *Yes, I think
   the minimum requirements on app academy open referred to "assets," so I
   used "positions" since that generalizes (includes assets such as options,
   bonds, cash, etc.)*
   - for watchlist users should be able to remove from their watchlist as
   well *Added this to MVP list. I had a route included for those in
   backend routes but I did not mention this in the MVP.*

Schema:

   - there are no companies tied to the trades, add a table referring to
   the company *The "ticker" identifier is unique to each asset. I was
   planning on using this for the API pulls to pull the share price, etc.
   Since this information is dynamic and often updates multiple times per
   second, I did not think it would make sense to store it in a database. Let
   me know if I'm misunderstanding anything.*
   - watchlists and companies should have a many-to-many relationship, so
   that watchlists can have many companies and companies can be on many
   watchlists. A joins table is necessary for this *See above, I was
   planning on using API pulls to populate the watchlist table information as
   opposed to having it stored in the database.*
