### ISSUE TITLE
Design Docs Review (Sample State + Backend/Frontend Routes)

### ISSUE THREAD

**Issue by rlim92** [danemauland/sheriff_of_nottingham#2]
Hey Dane, design docs looking good, some suggestions below: 

### Sample State: 
- [ ] The `displayed_assets` where does the `id` come from? I read over your response, I do feel a table may be useful here but we can discuss
- [ ] the `asset_watchlist` refers to the ids of the specific `positions` that the user is watching right? 
- [ ] in `session` slice of state, consider having a user object with their name instead of just an id if you don't want to have a separate `users` slice of state

### Backend Routes: 
- [ ] consider making `watchlist` GET route a show route with a wildcard

### Frontend Routes:
- [ ] consider adding a `Newsfeed` component (can fetch with external api) in the `Dashboard` route

Great work!

**Comment by danemauland** [comment]
Thanks for the feedback, responses below in *bold.*
Sample State:

   - The displayed_assets where does the id come from? I read over your
   response, I do feel a table may be useful here but we can discuss *id
   comes from the primary id in the watchlist table. Yes, looking forward to
   discussing*
   - the asset_watchlist refers to the ids of the specific positions that
   the user is watching right? *Yes, exactly*
   - in session slice of state, consider having a user object with their
   name instead of just an id if you don't want to have a separate users
   slice of state *Thanks, amended. Yeah, I'm not sure a users slice is
   needed given there's no interaction between users*

Backend Routes:

   - consider making watchlist GET route a show route with a wildcard *I
   was thinking each user would only have one watchlist, so I would use the
   currentUser's ID to pull their watchlist. I thought this would work best
   since users should not be able to view others' watchlists. By using just a
   get route and matching to currentUser's ID, no other code would be
   necessary to make sure no one is viewing someone else's watchlist.*

Frontend Routes:

   - consider adding a Newsfeed component (can fetch with external api) in
   the Dashboard route *Added, thank you.*
